(function(z){
var IL=function(a,b,c){b="new"===(b||a.qd);return c?(a=a.d.u.v().get(z.U.Mp),b?-1:-a):a.ll+(b?-1:1)};var JL=function(a){z.Rv.call(this,a);this.ll=0;this.qd="new"};var KL=function(a,b){a.rY=b};
var LL=function(a){return(0,z.Q)('\x3cdiv class\x3d"fyre '+(a.Od?"fyre-liveblog ":"")+(a.lh?"fyre-livechat ":"")+(a.KU?"fyre-bootstrap ":"")+(a.ue?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Va?"fyre-avatar-disabled":"")+'"\x3e'+(0,z.Q)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Va?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.yo?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var ML=function(a){return(0,z.Q)('\x3ca href\x3d"'+z.R(z.S(a.Aa))+'" title\x3d"'+z.R(a.ca)+'" aria-label\x3d"'+z.R(a.ca)+" "+z.R(a.j.profile)+'" data-id\x3d"'+z.R(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.R(a.sU)+'"\x3e\x3cimg src\x3d"'+z.R(z.S(a.Wc))+'" alt\x3d"'+z.R(a.ca)+" "+z.R(a.j.Wc)+'" onerror\x3d"javascript:this.src\x3d\''+z.R(z.ip(a.ec))+"';\" /\x3e\x3c/a\x3e")};
var NL=function(a){return(0,z.Q)(z.ir(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.P(a.j.RO)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(a.j.ry)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(a.j.cp)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(a.j.sy)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var OL=function(a){return(0,z.Q)('\x3cdiv class\x3d"tooltip"\x3e'+z.P(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var PL=function(){};var QL=function(a){this.ZG=!1;this.So=[];this.Bb=null;z.Gf.call(this,a)};var RL=function(a,b){z.Ij.call(this,b,a)};var SL=function(a,b){z.yG.call(this,a,b)};
var TL=function(a,b){var c=a.d.Kb;c.wh[4]&&(z.Ez(c,4,(0,z.t)(function(a){b.e(a,"threadBreakout",this.Wr)},a)),z.Gz(c,4,(0,z.t)(function(a){b.Fa(a,"threadBreakout",this.Wr)})))};var UL=function(a,b){var c=[a.xm,a.Jz];a.Hg&&c.push(a.Hg);a.Gt&&c.push(a.Gt);a.Kz&&c.push(a.Kz);z.y(c,function(a){z.ok(a,"fyre-stream-sort-selected")});z.mk(b,"fyre-stream-sort-selected")};var VL=function(a,b){z.yG.call(this,a,b)};
var WL=function(a,b){z.gy.call(this,a,b);this.kh=!1;this.kJ=!!this.C.L.bH;this.Ia=new z.py;this.Ia.uc(this);this.Fu="archiveShowMore"};var XL=function(a,b){z.vG.call(this,a,b)};var YL=function(a,b,c){z.ou.call(this,a,b,c);this.eA=b||"";this.Eg(OL(this.s()))};var ZL=function(a,b,c){z.iu.call(this,a,b||3,c)};var $L=function(a,b){z.T.call(this,b);this.l=a;this.Kt=z.W};var aM=function(a,b){z.T.call(this,b);this.Fc=a};var bM=function(a,b){aM.call(this,a,b)};
var cM=function(){var a=z.u.window,b=z.u.document;function c(){var a=w.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){w.SX||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(w,g)}function f(a){var b;if(a.aQ)return a;if(w.RX&&!l){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}q||(b=!d(a));b&&(a.aQ=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,l,q;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(l="hidden"in c)&&"function"==typeof a.FU&&a.FU("#modernizr{}",function(b){b.hidden=
!0;l="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});q=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var w={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.RX,shivMethods:!1!==g.SX,type:"default",shivDocument:f};f(b)};var dM=function(a,b){z.GG.call(this,a,b);a.L.VP||cM();var c=a.u.Ec(),d=a.u.v();this.ri=new z.wG(a,a.Xl.ya,d.lh()||z.eg);this.F(this.ri);a.L.Va||(this.Ln=new bM(c),this.F(this.Ln));this.ds=new z.uG;this.F(this.ds)};var eM=function(a){var b=z.F.nb()||z.F.get(z.E.Op);return!a.w.Od()||b};var fM=function(a){z.Nz.call(this,a);this.bn=1};
var gM=function(a){z.at.call(this,a);z.rv(a.u);this.Ub=new dM(a);this.gr.start();this.Nl(this.Ub);z.ft(this)};var hM=function(a,b){this.rD=RL;this.lK=gM;z.W.sm(b.strings||{});z.On.call(this,a,b);this.Ya.Mb.send(z.eo("Init"))};var iM=function(a){a.vk&&(a.vk.q(),delete a.vk)};z.v(JL,z.Rv);z.e=JL.prototype;z.e.yl=z.m(61);z.e.ZF=z.m(63);z.e.$F=z.m(62);z.e.ZF=z.K(63,function(a){this.La||(this.Oo[a]=!1,z.Sv(this,a,function(a){a.N(a.Ca.an)}))});
z.e.$F=z.K(62,function(a,b){if(!this.La){var c=this.d.u.v(),d=z.av(a,b),f=c.get(z.U.bu);c.set(z.U.Mp,d.YV);z.A(d.hb,(0,z.t)(this.d.U.N,this.d.U,"bootstrap_author_received"));d.content=z.kj(d.content,function(a,b){return!z.Ua(f,b)});z.A(d.content,function(a){z.lb(d.content,z.Uv(this,a))},this);z.lb(this.tc,z.jj(d.content,z.Eb(a)));this.de(a,d.content);z.Sv(this,a,function(b){b.N(b.Ca.Mk,{Rd:a});b.set(b.k.tf,!0)})}});
z.e.yl=z.K(61,function(a,b){this.ll=a;this.qd=b||this.qd;var c=this.Sd[a]=new z.Nv;z.Ru.D();var d=this.d.u.v(),f=(0,z.t)(this.$F,this,a),g=(0,z.t)(this.ZF,this,a),h=this.d.L.gn,d=d.get(z.U.yc),h=z.x.jv(d,h)+String(a)+".json";z.Su(0,h,f,g);return c});z.bH.prototype.yl=z.K(60,function(a,b){this.Wk||(this.Wk=new JL(this.C));var c=this.Wk,d=IL(c,a,b);return c.yl(d,a)});z.Ru.prototype.Yh=z.K(52,function(a,b,c){a=z.xa("%s%scollection/%s/hot/",z.x.H.Ed,z.x.of,a.ta);(new z.Qe({url:a,ua:b,oa:c})).send()});
z.hw.prototype.Yh=z.K(51,function(a){var b={ta:this.d.u.v().id},c=z.Ru.D().Yh;z.iw(this,c,b,a);return a});z.bH.prototype.Yh=z.K(50,function(){z.nw(this);this.Si=new z.hw(this.C,void 0);var a=new z.Nv;this.Si.Yh(a);return a});z.Ru.prototype.Uh=z.K(49,function(a,b,c){a=z.xa("%s%scollection/%s/top/%s/",z.x.H.Ed,z.x.of,a.ta,a.KO);(new z.Qe({url:a,ua:b,oa:c})).send({format:"stream"})});z.hw.prototype.Uh=z.K(48,function(a,b){var c={ta:this.d.u.v().id,KO:a},d=z.Ru.D().Uh;z.iw(this,d,c,b);return b});
z.bH.prototype.Uh=z.K(47,function(a){z.nw(this);this.Si=new z.hw(this.C,void 0);var b=new z.Nv;this.Si.Uh(a,b);return b});z.T.prototype.nH=z.K(46,function(){return this.aa});z.Fj.prototype.yo=z.K(45,function(){return this.get(this.k.Lp)});z.v(PL,z.Un);z.ca(PL);var jM={yZ:"attachmentDelegate"};z.lb(jM,z.tH);PL.prototype.vo=function(a){var b=PL.b.vo.call(this,a),c=a.attachmentDelegate;c&&(b.TO=c);b.ky=a[jM.tM]||null;return b};z.v(QL,z.Gf);QL.prototype.hV=function(a){this.Bb||(this.Bb=z.u.setInterval((0,z.t)(this.$Q,this),5E3));this.So=this.So.concat(a)};
QL.prototype.$Q=function(){this.So.length&&(this.ZG||(z.vc("//platform.twitter.com/impressions.js"),this.ZG=!0),z.u.twttr=function(){var a=z.u.twttr||{},b=a.impressions||{};b._e=b._e||[];b.ready=b.ready||function(a){b._e.push(a)};a.impressions=b;return a}(),z.u.twttr.impressions.ready((0,z.t)(function(a){a.impressions.logTweets(this.So,{partner:"livefyre"});this.So=[]},this)))};QL.prototype.q=function(){(0,window.clearInterval)(this.Bb);QL.b.q.call(this)};z.v(RL,z.Ij);RL.prototype.uz=function(a){this.Ru=new z.Zq(this,a);this.Mb=new z.Wn(this);this.Lc=new z.yi(this);this.u=new z.ov(this,a);this.kb=new z.Av(this,a);this.Nb=new z.bH(this,a);this.Xl=new z.Jv(this);new z.rf;this.ip=new z.Ow(this,a);this.Rz=new z.ow(this);this.Ni=new z.Dw(this);this.fA=new z.Tu(this,a);this.NY=new QL(this);this.Kb=new z.uz(this)};z.v(SL,z.yG);z.e=SL.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.fy=b.v().Od();a.VV=!z.F.get(z.F.k.Zd);a.Nd=b.Nd(z.F.id);a.YP=2===c.get(z.U.fj);a.XP=3===c.get(z.U.fj);a.j={$U:z.W.get(z.W.g.tu),dV:z.W.get(z.W.g.uu),qU:z.W.get(z.W.g.yB),ry:z.W.get(z.W.g.gq),sy:z.W.get(z.W.g.hq),cp:z.W.get(z.W.g.zC),tp:z.W.get(z.W.g.lq),FY:z.W.get(z.W.g.QC)};return a};
z.e.K=function(a){SL.b.K.call(this,a);a=this.c;var b;b=this.s();var c=z.Q,d=z.ir(b),f;f=b.fy?(0,z.Q)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.VV?b.Nd?z.P(b.j.dV):z.P(b.j.$U):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(b.j.ry)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.cp)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(b.j.sy)+"\x3c/a\x3e"+(b.YP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.cp)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+z.P(b.j.FY)+"\x3c/a\x3e":"")+(b.XP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.cp)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+z.P(b.j.qU)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.xl=this.o("fyre-follow-conversation");this.Gt=this.o("fyre-stream-sort-hot-threads")||
null;this.Kz=this.o("fyre-stream-sort-top-comments")||null;this.Hg=this.o("fyre-stream-sort-back");this.xm=this.o("fyre-stream-sort-newest");this.Jz=this.o("fyre-stream-sort-oldest");this.pJ=this.o("fyre-stream-sort-options");this.ed=this.o("fyre-content-loading");this.Kd()};z.e.m=function(){SL.b.m.call(this);var a=this.p();z.F.on(z.F.Ca.$f,this.no,this);a.e(this.c,"click",this.mb);z.y([3,4,5],function(b){z.zG(this,a,b)},this);TL(this,a)};
z.e.mb=function(a){a.preventDefault();a=a.target;if(!z.sk(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.Hg)if(a===this.xl)this.WF();else{UL(this,a);this.wm();var b=null;switch(a){case this.Gt:this.GE();b="hottest";break;case this.Kz:this.dispatchEvent({type:"sortTopComments",Yb:(0,z.t)(this.Kd,this)});b="top_comments";break;case this.xm:this.An("new");b="newest";break;case this.Jz:this.An("old"),b="oldest"}this.d.Mb.send(z.eo("SortStream",{Ns:b}))}};
z.e.Ki=function(a,b){a&&this.vz(b);z.El(this.pJ,"display",a?"none":"block");z.El(this.Hg,"display",a?"block":"none")};z.e.vz=function(a){var b=this.xm,c=this.An,d=z.W.get(z.W.g.cu);4===a&&(b=this.Gt,c=this.GE,d=z.W.get(z.W.g.zK));this.Hg.innerHTML=d;this.p().Pd(this.Hg,"click",(0,z.t)(function(a){a.stopPropagation();this.Ki(!1);UL(this,b);c.apply(this)},this))};z.e.io=function(a){a.stopPropagation();this.Ki(!1);UL(this,this.xm);this.An()};
z.e.Wr=function(a){var b=a.Yb;z.lb(a,{Yb:(0,z.t)(function(){b();this.Ki(!0,4)},this)})};z.e.An=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Yb:(0,z.t)(this.Kd,this)})};z.e.GE=function(){this.dispatchEvent({type:"sortHotThreads",Yb:(0,z.t)(this.Kd,this)})};z.e.WF=function(){var a=this.d.u;a.v();var b=z.F.k;z.F.id?(b=a.Nd(z.F.get(b.Y)),a.Fj(!b),a=b?z.W.get(z.W.g.tu):z.W.get(z.W.g.uu),this.xl.innerHTML=a):z.Th(this.d.Lc,(0,z.t)(this.WF,this))};
z.e.no=function(){var a=this.d.u,b=a.v(),c=z.F.k,b=!b.Od()||z.F.get(c.Zd);this.xl&&(b?z.N(this.xl,!1):(a=a.Nd(z.F.id)?z.W.get(z.W.g.uu):z.W.get(z.W.g.tu),this.xl.innerHTML=a,z.N(this.xl,!0)))};z.e.h=function(){SL.b.h.call(this);z.F.off(null,null,this)};z.v(VL,SL);VL.prototype.K=function(a){this.c=a;z.Ao(a,NL,this.s());this.xm=this.o("fyre-stream-sort-newest");this.Jz=this.o("fyre-stream-sort-oldest");this.pJ=this.o("fyre-stream-sort-options");this.ed=this.o("fyre-content-loading");this.Kd()};VL.prototype.An=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.rY.stream,direction:a,Yb:(0,z.t)(this.Kd,this)})};
VL.prototype.s=function(){return{j:{RO:z.W.get(z.W.g.uK),ry:z.W.get(z.W.g.gq),sy:z.W.get(z.W.g.hq),cp:z.W.get(z.W.g.zC),tp:z.W.get(z.W.g.lq)}}};z.v(WL,z.gy);z.e=WL.prototype;z.e.qn=function(a){this.clear();z.N(this.c,!0);this.qd=a};z.e.clear=function(){this.od.Pf();this.wb={};this.Nj=[];for(this.xh=this.$k=null;this.ma&&0!=this.ma.length;)this.Vo(0).q()};z.e.K=function(a){WL.b.K.call(this,a);z.Ao(this.c,z.jr,this.s());this.nk=this.o("fyre-stream-content");this.Li=this.o("fyre-stream-more");this.Ia.S(this.Li);z.N(this.Li,!1)};z.e.h=function(){this.Ia&&this.Ia.q();this.Ia=null;WL.b.h.call(this)};
z.e.m=function(){WL.b.m.call(this);this.p().e(this.Ia,"showMore",this.ox)};z.e.rw=function(){return this.C.L.bH};z.e.s=function(){return{ee:z.x.H.pb,Hv:!!this.Ia,j:{Bz:z.W.get(z.W.g.vK)}}};z.e.px=function(){this.Ia.Bt();this.kh=!0};z.e.Iy=function(){this.dispatchEvent({type:this.Fu,direction:this.qd,target:this,VY:this.kh&&this.kJ,Yb:(0,z.t)(this.px,this),Ej:(0,z.t)(this.zG,this)});this.kh&&(this.kJ=!1)};z.e.Py=function(a){this.kh||WL.b.Py.call(this,a)};
z.e.hp=function(){var a=this.C.Nb.Wk,b=this.qd,c=a.d.u.v(),b="old"===b,c=c.get(z.U.Mp),c=!b&&a.ll>-c;b&&-1>a.ll||c?this.Ia.show():this.Ia.sb()};z.e.start=function(){this.kh||this.Iy()};z.v(XL,z.vG);var kM=z.W.g,lM={};lM.comment=[kM.Xm,kM.ag,kM.Mm];lM.liveblog=[kM.XM,kM.hM,kM.EB];XL.prototype.sF=function(a){function b(a){return z.Ha(a,"%s")?a:"%s "+a}var c=this.l.Od()?"liveblog":"comment",c=lM[c];switch(a){case 1:c=b(z.W.get(c[1]));break;case 0:if(z.W.get(c[0])!==z.tG[c[0]]){c=z.W.get(c[0]);break}default:c=b(z.W.get(c[2]))}return z.xa(c,a)};z.v(YL,z.ou);YL.prototype.kp=200;YL.prototype.$h=function(){return new ZL(this.Kc)};YL.prototype.s=function(){var a={};a.message=this.eA;return a};z.v(ZL,z.iu);ZL.prototype.Rc=function(a,b,c){var d=z.cm(this.element),d=new z.Dh(d.width,d.height+25);b=z.du(this.element,this.Oh,a,b,d,c,9);z.Kl(a.lastChild,0);b&&(d=new z.Dh(0,-5),z.du(this.element,2,a,1,d,c,5),z.Kl(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.v($L,z.T);z.e=$L.prototype;z.e.r=function(){this.c=z.Do(ML,this.s())};z.e.m=function(){$L.b.m.call(this);this.Xa=new YL(this.c,this.l.get("displayName"));this.p().e(this.c,"click",this.mb)};z.e.h=function(){$L.b.h.call(this);this.Xa&&this.Xa.q()};z.e.s=function(){var a=z.Wd,b=this.Kt,c={};c.Wc=this.l.get(a.yb);c.ec=this.l.get(a.Bk);c.ca=this.l.get(a.va);c.id=this.l.id;c.sU=this.l.id.replace(/[@.]/g,"-");c.Aa=this.l.get(a.ac);c.j={profile:b.get(b.g.eM),Wc:b.get(b.g.cM)};return c};
z.e.mb=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.l,type:"author_click"})};z.v(aM,z.T);z.e=aM.prototype;z.e.IB=10;z.e.h=function(){aM.b.h.call(this);delete this.Fc};z.e.R=function(){aM.b.R.call(this);this.Fc.off(null,null,this)};z.e.GF=function(a){a=new $L(a);var b=this.Pc();if(b===this.IB){var c=this.Vo(b-1);c&&(c.q(),b--)}0<b?this.Je(a,0,!0):this.F(a,!0)};z.e.wT=function(a){var b;this.Oc(function(c){a.id===c.l.id&&(b=c)});b&&(this.removeChild(b),b.q())};
z.e.jo=function(){this.Fc.on(this.Fc.Ca.au,this.GF,this);this.Fc.on(this.Fc.Ca.Bu,this.wT,this);var a=this.Fc.jb.reverse().slice(0,this.IB);z.y(a,this.GF,this)};z.v(bM,aM);z.v(dM,z.GG);
dM.prototype.FI=function(a,b){if(!this.La){this.w=b;var c=b.get(z.U.Fh),d=b.get(z.U.ae);this.Vt=new z.DG(c,d,a.L.Va);this.F(this.Vt);this.Rq=new XL(a.u.v());this.F(this.Rq);this.Js=null;b.yo()&&(this.bv=new VL(a),this.F(this.bv),this.Xk=new WL(a),this.F(this.Xk),KL(this.bv,{stream:this.Xk}));this.uh=new SL(a);this.F(this.uh);this.Bs((0,z.t)(function(a){this.fc=a;this.F(this.fc);a=this.fc;this.aa&&a&&a.S(this.me,!0)},this));b.get(z.U.Sm)&&!z.eg&&this.w.nr()&&(this.w.lh()||this.w.Od()||this.Uw())}};
dM.prototype.s=function(){return{Va:this.d.L.Va,lh:this.w.lh(),Od:this.w.Od(),ue:z.eg,KU:this.d.L.BD,yo:this.w.yo()}};z.vy={uZ:"fyre-archive-stream",vZ:"fyre-archive-stream-header",o2:"fyre-top-content-stream",I2:"fyre-widget",Sm:"fyre-featured-content-wrapper"};z.lb(z.vy,z.tK);z.e=dM.prototype;
z.e.r=function(){this.c=z.Do(LL,this.s());var a=this.w.get(z.U.fj);if(1!==a){var b=this.d.Kb,a=2===a?3:4,c=this.o("fyre-top-content-stream");z.vz(b,a,c,this)}this.ds.S(this.o(z.vy.RL));this.Xk&&(b=this.o("fyre-archive-stream-header"),this.bv.S(b),this.Xk.S(this.o("fyre-archive-stream")));this.Ph(1);this.me=this.o(z.vy.Ch);b=eM(this);z.N(this.me,b)};
z.e.m=function(){dM.b.m.call(this);var a=this.fc;this.aa&&a&&a.S(this.me,!0);this.d.U.vp("stream_data_received",this.yS,this);this.p().e(this,"request_content_context",this.XR).e(this,"request_content_reply",this.zT);this.Xk&&this.Xk.start()};z.e.jo=function(){this.Ln&&this.Ln.jo()};z.e.yS=function(){var a=this.w,b=a.get(z.U.Fk);z.uh||b||(b=(0,z.t)(function(){this.Js=new z.mM(this.d,a.get(z.U.ae));this.F(this.Js,!0)},this),z.vc(z.x.H.pb+z.x.Kf.Js,null,null,b))};
z.e.Uw=function(){var a=new z.lF(this.nH,this);a.fI=(0,z.t)(this.nX,this);var b=(0,z.t)(function(){a.start(0,2E3)},this);z.vc(z.x.H.pb+z.x.Kf.EQ,null,null,b)};z.e.nX=function(){var a=this.o("fyre-featured-content-wrapper");this.aw=new z.JK(this.d);this.F(this.aw);this.aw.S(a);this.aw.jh()};z.e.Bs=function(a){if(!this.d.L.readOnly){var b=this.d.u.v();z.jx(z.gx.D(),"main",a,{C:this.d,Ci:"new"},b);z.F.on(z.F.nc(z.F.k.Y),this.$c,this)}};z.e.$c=function(){if(this.me){var a=eM(this);z.N(this.me,a)}};
z.e.ei=function(){0<z.Kp(this,this.fc)&&(this.removeChild(this.fc),this.fc.q());this.Bs((0,z.t)(function(a){this.fc=a;this.F(this.fc);a=this.fc;this.aa&&a&&a.S(this.me,!0);z.N(this.me,!0)},this))};z.e.ih=function(a,b){null!=a&&(this.d.Kb.Cl(1),(0,window.setTimeout)((0,z.t)(function(){var c=b&&function(a){z.fx(a.Qa)};this.La||z.HG(this,a,c)},this),3E3))};z.e.XR=function(a){z.HG(this,a.dl)};z.e.zT=function(a){z.HG(this,a.dl,function(a){z.fx(a.Qa)})};
z.e.h=function(){dM.b.h.call(this);z.F.off(z.F.nc(z.F.k.Y),this.$c,this);this.w&&(this.w.off(null,null,this),this.w=null)};z.v(fM,z.Nz);z.e=fM.prototype;z.e.re=function(a,b){fM.b.re.call(this,a,b);a.e(b,"repliesExpanded",this.TF);a.e(b,"sortHotThreads",this.KT);a.e(b,"sortOrderChanged",this.CG);a.e(b,"sortTopComments",this.LT);a.e(b,"archiveShowMore",this.GR);a.e(b,"archiveSortOrderChanged",this.HR)};
z.e.GR=function(a){var b=a.Yb||z.n,c=(0,z.t)(this.We,this,a.target),d=this.d.Nb;a=a.VY;d.Wk||(d.Wk=new JL(d.C));d=d.Wk;a=a?d.ll:IL(d);var f=d.fd[a];f&&(d.ll=a);if(f)b(),c(f);else{d=this.d.Nb.yl();a=d.k.tf;if(d.get(a))b();else d.on(d.nc(a),b,this);z.Oz(this,d,c)}};z.e.Pw=function(a,b){var c=2===b.gd,d=1!==b.gd;switch(b.type){case 0:var f=this.d.u.v(),f=z.Om(b,f),g=f.get(z.cn),g=this.d.u.hb().get(g);f.set(z.Pm,g);a.fx(f,c,d)}};
z.e.sG=function(a){if(1!==this.bn){var b=this.jY.uh;b.Ki(!1);UL(b,b.xm);z.lb(a,{direction:"new",Yb:z.n});this.CG(a)}};z.e.HR=function(a){z.Pz(this);a.stream.qn(a.direction);var b=this.d.Nb.yl(a.direction,!0),c=(0,z.t)(function(b){a.Yb();this.We(a.stream,b)},this);z.Oz(this,b,c,a.Ej)};z.e.CG=function(a){this.d.L.ki=null;var b=z.Rz(this,1);z.nw(this.d.Nb);b.qn(a.direction);var c=z.mw(this.d.Nb,a.direction),d=(0,z.t)(function(c){a.Yb();this.We(b,c)},this);z.Oz(this,c,d,a.Ej)};
z.e.LT=function(a){var b=z.Rz(this,3),c=this.d.Nb.Uh("likes");z.Oz(this,c,(0,z.t)(function(c){a.Yb();z.ib(c)?z.fy(b):this.We(b,c)},this))};z.e.KT=function(a){var b=z.Rz(this,4),c=this.d.Nb.Yh();z.Oz(this,c,(0,z.t)(function(c){a.Yb();z.ib(c)?z.fy(b):this.We(b,c)},this))};z.v(gM,z.at);z.e=gM.prototype;z.e.c=null;z.e.h=function(){gM.b.h.call(this);this.It.q();this.WD.q();this.Ub.aa&&this.Ub.q();this.Zf&&this.Zf.q();delete this.Zf};z.e.Nl=function(a){gM.b.Nl.call(this,a);this.It=new fM(this.d);this.It.handle(a);this.WD=new z.Kz(this.d);this.WD.handle(a)};z.e.Sz=function(){this.d.Ni.stop()};z.e.qY=function(){this.d.Xl.stop()};z.e.kk=function(){this.d.Ni.start()};z.e.nY=function(){this.d.Xl.start()};
z.e.ra=function(){this.Zf&&this.Zf.q();this.Ub.ra(this.c);this.d.Mb.send(z.eo("Load"));var a=z.ct(window.location,"reply_editor");if("object"===typeof window.Livefyre&&window.Livefyre.CO)z.gt(this,a);else{var b=z.dt(this);this.Ub.ih(b,a)}this.d.U.N("render_complete",this.c)};z.v(hM,z.On);hM.prototype.mD=PL.D();hM.prototype.h=function(){hM.b.h.call(this);this.stop();delete this.L;delete this.ha;iM(this);z.Tn(this);this.Dj&&(this.Dj.q(),delete this.Dj)};hM.prototype.$z=function(){this.stop();iM(this);hM.b.$z.call(this)};z.mg.main.Qh.ia(hM);})(fyre.conv);
